name: Object storage tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pip install testtools
      - run: pip install Werkzeug
      - run: pip install Flask
      - run: pip install SQLAlchemy
      - run: pip install Flask-SQLAlchemy
      - run: pip install flask-json-schema
      - run: pip install flask-expects-json
      - run: pip install toml
      - run: python3 -m testtools.run
      - run: echo "ğŸ This job's status is ${{ job.status }}."